name: Release

on:
  workflow_dispatch
  #release:
  #  types: [published]

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x

      - name: Publish application
        run: dotnet publish MicroNotes/MicroNotes.csproj -c Release -o publish -r win-x64 --self-contained true
      
      - name: debug
        run: tree

      #- name: Create release package
      #  run: |
      #    dotnet tool install -g vpk
      #    vpk download github --repoUrl https://github.com/koglerch13/micronotes
      #    vpk pack -u app.ckogler.MicroNotes -v ${{ github.event.release.tag_name }} -p MicroNotes/publish -e MicroNotes.exe --packTitle MicroNotes
      #    vpk upload github --repoUrl https://github.com/koglerch13/micronotes --publish --releaseName "${{ github.event.release.tag_name }}"

        
